'use client';

import {
  Home,
  Flame,
  CheckCircle2,
  User,
  GraduationCap,
  MessageSquare,
  LayoutDashboard,
  Siren,
  Calculator,
  FileCheck2,
  Users,
  Truck,
  ClipboardCheck,
  Package,
  CalendarClock,
  FolderOpen,
  Calendar,
  Building2,
  Scale,
  ShieldAlert,
  FileSearch,
  Globe2,
  FlagTriangleRight,
  BarChart3,
  Megaphone,
  Plug,
  // Nuevos iconos para páginas Fase 1-8
  Radio,
  Sparkles,
  FileText,
  Shield,
  Stethoscope,
  Droplets,
  TrendingUp,
  FileBarChart,
  Wand2,
  Eye,
  Antenna,
  Database,
  Map,
  Hash,
  // Iconos módulo Finanzas
  PiggyBank,
  ArrowLeftRight,
  Landmark,
  BadgeDollarSign,
  ListTree,
  Target,
  Receipt,
  FileSpreadsheet,
  // Federación red
  BookMarked,
  UsersRound,
  // Organización
  Network,
  ClipboardList,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  home: Home,
  flame: Flame,
  'check-circle-2': CheckCircle2,
  user: User,
  'graduation-cap': GraduationCap,
  'message-square': MessageSquare,
  'layout-dashboard': LayoutDashboard,
  siren: Siren,
  calculator: Calculator,
  'file-check-2': FileCheck2,
  users: Users,
  truck: Truck,
  'clipboard-check': ClipboardCheck,
  package: Package,
  'calendar-clock': CalendarClock,
  'folder-open': FolderOpen,
  calendar: Calendar,
  'building-2': Building2,
  scale: Scale,
  'shield-alert': ShieldAlert,
  'file-search': FileSearch,
  'globe-2': Globe2,
  'flag-triangle-right': FlagTriangleRight,
  'bar-chart-3': BarChart3,
  megaphone: Megaphone,
  plug: Plug,
  // Nuevos
  radio: Radio,
  sparkles: Sparkles,
  'file-text': FileText,
  shield: Shield,
  stethoscope: Stethoscope,
  droplets: Droplets,
  'trending-up': TrendingUp,
  'file-bar-chart': FileBarChart,
  'wand-2': Wand2,
  eye: Eye,
  antenna: Antenna,
  database: Database,
  map: Map,
  hash: Hash,
  // Finanzas
  'piggy-bank': PiggyBank,
  'arrow-left-right': ArrowLeftRight,
  landmark: Landmark,
  'badge-dollar-sign': BadgeDollarSign,
  'list-tree': ListTree,
  target: Target,
  receipt: Receipt,
  'file-spreadsheet': FileSpreadsheet,
  'book-marked': BookMarked,
  'users-round': UsersRound,
  network: Network,
  'clipboard-list': ClipboardList,
};

export function Icon({
  name,
  size = 20,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const C = iconMap[name];
  if (!C) return null;
  return <C size={size} className={className} aria-hidden />;
}
